"""Removed Token fron User, Added UserMixer and OAuth table to Model

Revision ID: 1ab080a61204
Revises: 4d9889c4fb5c
Create Date: 2019-01-04 23:16:07.098950

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '1ab080a61204'
down_revision = '4d9889c4fb5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flask_dance_oauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('token', sqlalchemy_utils.types.json.JSONType(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_flask_dance_oauth_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flask_dance_oauth'))
    )
    op.drop_constraint('uq_users_token', 'users', type_='unique')
    op.drop_column('users', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.create_unique_constraint('uq_users_token', 'users', ['token'])
    op.drop_table('flask_dance_oauth')
    # ### end Alembic commands ###
