"""Added a token column to the User Model

Revision ID: c79e8f9b9b39
Revises: 1867107fae82
Create Date: 2019-01-03 07:02:03.569253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c79e8f9b9b39'
down_revision = '1867107fae82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'users', ['token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'token')
    # ### end Alembic commands ###
